version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    hostname: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  pwa:
    hostname: pwa-docker.local
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - nginx-proxy
    environment:
      VIRTUAL_HOST: pwa-docker.local
      VIRTUAL_PORT: 8080
    expose:
      - 8080
    
