version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    hostname: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  pwa:
    hostname: ${PWA_STUDIO_PUBLIC_PATH}
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - nginx-proxy
    environment:
      VIRTUAL_HOST: ${PWA_STUDIO_PUBLIC_PATH}
      VIRTUAL_PORT: ${PWA_STUDIO_PORTS_DEVELOPMENT}
    expose:
      - ${PWA_STUDIO_PORTS_DEVELOPMENT}
